version: 0.0
os: linux
files:
  - source: studyspring-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
